### ISSUE TITLE
does not builds with boost 1.63

### ISSUE THREAD

**Issue by sss123next** [hanzz/spectrum2#193]

**Comment by vitalyster** [comment]
Any relevant error message ?

**Comment by sss123next** [comment]
```
In file included from /var/tmp/paludis/net-im-spectrum-scm/work/spectrum-scm/include/transport/User.h:30:0,
                 from /var/tmp/paludis/net-im-spectrum-scm/work/spectrum-scm/libtransport/Buddy.cpp:23:
/usr/include/Swiften/Elements/Message.h: In member function 'bool Swift::Message::hasSubject()':
/usr/include/Swiften/Elements/Message.h:42:32: error: cannot convert 'boost::shared_ptr<Swift::Subject>' to 'bool' in return
     return getPayload<Subject>();

```


looks like swiften problem ...

**Comment by vitalyster** [comment]
which swiften version you are using?

**Comment by sss123next** [comment]
2x git branch as recommended here https://github.com/hanzz/spectrum2/blob/master/docs/guide/from_source_code.textile

**Comment by vitalyster** [comment]
This recommendation is outdated, spectrum already supports swiften 3.x and 4.x

**Comment by sss123next** [comment]
works with 4.x, thx for info.
